import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider, UserButton } from "@clerk/nextjs";
import { dark } from "@clerk/themes";

const inter = Inter({ subsets: ["latin"] });

if (!process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY) {
  throw new Error("Missing Publishable Key");
}
const clerkPubKey = process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY;

export const metadata = {
  title: "Next Todos",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider publishableKey={clerkPubKey} appearance={dark}>
      <html lang="en">
        <body className={inter.className}>
          <header className="app-header">
            <h1>{metadata.title}</h1>
            <UserButton />
          </header>
          <main className="app-content">{children}</main>
        </body>
      </html>
    </ClerkProvider>
  );
}
